### ISSUE TITLE
How can we get the userauthentication in DevOps?

### ISSUE THREAD

**Issue by cheahengsoon** [h4wkst3r/ADOKit#2]
Hi,
I'm new to AzureDevOps some confuse of this credential:"UserAuthentication=ABC123", 
May I ask about how we get the credential from Azure DevOps?
Thank you

**Comment by h4wkst3r** [comment]
When a user has authenticated to Azure DevOps Services, there is a cookie set with the name `UserAuthentication`. I have details on this in the `Initial Access` section in my whitepaper linked in the README file.
